### PR TITLE
#447: [ResizeSensor] throws error on detach (closes #447)

### LINKED ISSUE #447: [ResizeSensor] throw error on detach
## description
throws error when updating after children have changed due to the detach failing

## how to reproduce
- {optional: describe steps to reproduce bug}

## specs
after [inspecting the lib code](https://github.com/marcj/css-element-queries/blob/master/src/ResizeSensor.js) I can say that:
- the cleaning `detach` is useless as everything is stored inside the `element` and there's no `removeEventListener` in the code
  - when attaching it creates variables in `element` and add a children node inside it
  - when `children` changes the previous `element` is removed from the DOM --> we can skip the "cleaning"
- the attach action works only if `!element.resizedAttached`
  - we should make a redundant check just in case before attaching a new resize sensor

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Issue #447

### tests performed
- button + textoverflow example now works without errors
- tested on LOL too

### tests not performed (domain coverage)
I assumed a couple of things, read them in issue specs

### CODE REVIEW

File: src/resize-sensor/ResizeSensor.js [hunk 1]
```diff
@@ -1,51 +1,42 @@
...
     _ElementQueries.listen();
-    this.updateResizeSensor();
+    this.attachResizeSensor();
   }
 
   componentDidUpdate() {
-    this.updateResizeSensor();
-  }
-
-  componentWillUnmount() {
```
Comment (giogonzo) [inline src/resize-sensor/ResizeSensor.js]: I think your assumptions on not needing to `detach()` are correct, but what's the cost of adding a call to detach here? So that we are 100% sure we're cleaning everything up...

`if !!findDOMNode()` should be enough to make ti safe?

**Comment by giogonzo** [comment]
👍 except for inline proposal

File: src/resize-sensor/ResizeSensor.js (hunk 1 above)
Comment (FrancescoCioria) [inline src/resize-sensor/ResizeSensor.js]: In `componentDidUpdate` this is not true as `findDOMNode` will always be `true` because of  the newly `this.refs.text` already being rendered... (we should check if it contains the resize element added by `ResizeSensor` to understand if there's something to detach or not).

Nevertheless we *should* be able to call it on `componentWillUnmount`, do you think it could be enough adding it in `cwum`?

Comment (giogonzo) [inline src/resize-sensor/ResizeSensor.js]: yes didn't specify but I'm talking about `cwum`

Comment (FrancescoCioria) [inline src/resize-sensor/ResizeSensor.js]: nope, `Button` + `TextOverflow` throws an error for the reason I wrote above... If you agree I would leave it as it is and, if we have performance issues, find a way to determine if contains or not the resize sensor element (I wanted to avoid this as it would need a css query selector which we'll then need to keep up to date)

Comment (FrancescoCioria) [inline src/resize-sensor/ResizeSensor.js]: opened https://github.com/buildo/react-components/issues/453 : we can continue the discussion there (so to unblock other PRs and LOL which is currently broken)
