### PR TITLE
#825: timePicker doesn't update the options with new input value (closes #825)

### LINKED ISSUE #825: timePicker doesn't update the options with new input value
## description
When the user manually enter an input value the did not already exist in the options, `TimePicker` doesn't update the options list with the new value.

## how to reproduce
* in one of the examples of the timepicker component initialize a state value of non existed option, for example:
state = { value: { hours: 10, minutes: 32 }}
* start the application: the timepicker of the example would not populate the initial value.

## specs
In the function of makeOptions, make sure to add the inputValue.

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by sawsanias**
Closes #825

## Test Plan

* run the application, and check the 24H TimePicker, the value 11:23 should be selected.
825-timepicker_doesnt_update_the
image

* Open the dropdown menu, and see the option 11:23 within the options and in the right order
image

* retry by entering new value e.g. 08:33
image

* retry by enter the value 08:02 (value is not within the range)
image

* Change the state value of TimePicker12.js by: `state = { value: { hours: 11, minutes: 23 } }`
image
 start typing 11:
image

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.

- [ ] Google Chrome
- [ ] Internet Explorer

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.

### CODE REVIEW

**Comment by sawsanias** [comment]
@francescogior I am not sure about H12 timeformat, should I consider to populate just one value?

File: src/time-picker/TimePicker.js [hunk 1]
```diff
@@ -136,13 +139,17 @@ export const filterTime = ({ originalInput, minTime, maxTime }) => time => {
...
 };
 
-export const makeOptions = ({ minTime, maxTime, timeFormat }, inputValue) => {
+export const makeOptions = ({ minTime, maxTime, timeFormat, userValue }, inputValue) => {
   const time = parseInTimeFormat(inputValue, timeFormat);
-  const timeList = time === inputError ? [] : createTimeList(time, timeFormat);
+  //make sure the userValue has timeFormat so in H12 the day period will be shown
+  if ( userValue && userValue !== inputError ) {
+    userValue.timeFormat = timeFormat;
+  }
```
Comment (francescogior) [inline src/time-picker/TimePicker.js]: remove 144:147, you're not using `timeFormat` anywhere

File: src/time-picker/TimePicker.js [hunk 2]
```diff
@@ -136,13 +139,17 @@ export const filterTime = ({ originalInput, minTime, maxTime }) => time => {
...
+  const timeList = time === inputError ? [] : createTimeList(time, timeFormat).concat(compact([userValue]));
```
Comment (francescogior) [inline src/time-picker/TimePicker.js]: The correct way would be
```js
const timeList = (time === inputError ? [] : createTimeList(time, timeFormat)).concat(compact([userValue]));
```
ie you concat the `userValue` even if the `time === `inputError` (but see related comment below)

File: src/time-picker/TimePicker.js [hunk 3]
```diff
@@ -136,13 +139,17 @@ export const filterTime = ({ originalInput, minTime, maxTime }) => time => {
...
   const filteredTimeList = timeList.filter(filterTime({
     originalInput: time.originalInput, minTime, maxTime
```
Comment (francescogior) [inline src/time-picker/TimePicker.js]: `originalInput: time.originalInput || ''` because it can be undefined and it'd break in the `filterTime` (precisely in the `startsWith`) function

**Comment by francescogior** [comment]
@sawsanias also there's a eslint error to fix that breaks the ci

`144:3  error  Expected space or tab after '//' in comment  spaced-comment`

File: src/time-picker/TimePicker.js (hunk 1 above)
Comment (sawsanias) [inline src/time-picker/TimePicker.js]: if you don't set the TimeFormat, it will consider it as H24 and will show the option as:

image


it is used in 

`const formatTime = ({ hours, minutes, timeFormat }) => (
  timeFormat === H12 ? formatTime12({ hours, minutes }) : formatTime24({ hours, minutes })
);`

Comment (francescogior) [inline src/time-picker/TimePicker.js]: You're right!
Still, I don't like to modify function parameters. I'll leave a comment in the next review

File: src/time-picker/TimePicker.js [hunk 4]
```diff
@@ -141,13 +141,12 @@ export const filterTime = ({ originalInput, minTime, maxTime }) => time => {
 
 export const makeOptions = ({ minTime, maxTime, timeFormat, userValue }, inputValue) => {
   const time = parseInTimeFormat(inputValue, timeFormat);
-  //make sure the userValue has timeFormat so in H12 the day period will be shown
   if ( userValue && userValue !== inputError ) {
```
Comment (francescogior) [inline src/time-picker/TimePicker.js]: do not update function parameters:
```
const selectedValue = (userValue && userValue !== inputError) ? { ...userValue, timeFormat } : userValue
```

File: src/time-picker/TimePicker.js [hunk 5]
```diff
@@ -141,13 +141,12 @@ export const filterTime = ({ originalInput, minTime, maxTime }) => time => {
...
     userValue.timeFormat = timeFormat;
   }
-  const timeList = time === inputError ? [] : createTimeList(time, timeFormat).concat(compact([userValue]));
+  const timeList = (time === inputError ? [] : createTimeList(time, timeFormat)).concat(compact([userValue]));
```
Comment (francescogior) [inline src/time-picker/TimePicker.js]: and then 
```js
...)).concat(compact([selectedValue]);
```

File: src/time-picker/TimePicker.js [hunk 6]
```diff
@@ -136,13 +139,14 @@ export const filterTime = ({ originalInput, minTime, maxTime }) => time => {
...
 
-export const makeOptions = ({ minTime, maxTime, timeFormat }, inputValue) => {
+export const makeOptions = ({ minTime, maxTime, timeFormat, userValue }, inputValue) => {
   const time = parseInTimeFormat(inputValue, timeFormat);
-  const timeList = time === inputError ? [] : createTimeList(time, timeFormat);
+  const selectedValue = (userValue && userValue !== inputError) ? { ...userValue, timeFormat } : userValue;
+  const timeList = (time === inputError ? [] : createTimeList(time, timeFormat)).concat(compact([selectedValue]));
   const filteredTimeList = timeList.filter(filterTime({
-    originalInput: time.originalInput, minTime, maxTime
+    originalInput: time.originalInput || '', minTime, maxTime
```
Comment (ascariandrea) [inline src/time-picker/TimePicker.js]: I would edit this function (or add a second `.filter` step) by filtering also `undefined` values to avoid the `.concat(compact([selectedValue]))`.

**Comment by francescogior** [comment]
tested on internal project and fix the related bug 👍
