### PR TITLE
#899: Warnings while installing (closes #899)

### LINKED ISSUE #899: Warnings while installing
## description
```
yarn install v0.24.6
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning buildo-react-components > react-addons-transition-group@15.5.2: This package is deprecated and will no longer work with React 16+. We recommend you use TransitionGroup from 'react-transition-group' instead.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "revenge@0.4.5" has incorrect peer dependency "react@^0.13.3 || ^0.14".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 3.68s.
```

## how to reproduce
- yarn init
- yarn add react react-dom
- yarn add react-components

### PR DESCRIPTION
**Pull request by gabro**
Closes #899

### tests performed
- tests pass
- showroom starts
- toaster still works
- modal still works

### CODE REVIEW

File: src/tablo/plugins/selectable/selectableGrid.js [hunk 1]
```diff
@@ -53,7 +53,6 @@ const getLocals = ({
 export default (Grid) =>
 
   @skinnable(contains(Grid))
-  @pure
   @props(propsTypes, { strict: false })
   class SelectableGrid extends React.Component {
```
Comment (FrancescoCioria) [inline src/tablo/plugins/selectable/selectableGrid.js]: you forgot this one?

Comment (gabro) [inline src/tablo/plugins/selectable/selectableGrid.js]: yes, good catch!

**Comment by gabro** [comment]
ok, all done! 💯
