### PR TITLE
#436: [TextOverflow] Should update also on parent resize (closes #436)

### LINKED ISSUE #436: [TextOverflow] Should update also on parent resize
## description
as for title

## how to reproduce
- put `TextOverflow` in a resizable container

## specs
- attach to the resize event and calculate the overflow on each resize

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Issue #436

### tests performed
[https://gyazo.com/865b67f71e952420b4b6c9e901f8ad1a](https://gyazo.com/865b67f71e952420b4b6c9e901f8ad1a)

#### cross browser compatibility
I didn't directly tested it on IE11 but the only browser-dependent logic is in `ResizeSensor` which works on IE11

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
@giogonzo what do you think?

pro:
- we can keep `@pure` on wrapper
- robust (I think interval is the only robust way to verify changes of width)
cons:
- will it affect performance?? (we're using `TextOverflow` quite heavily in lol)

File: src/text-overflow/TextOverflow.js [hunk 1]
```diff
@@ -54,21 +64,35 @@ export default class TextOverflow extends React.Component {
...
+    const width = this.getElementWidth(ReactDOM.findDOMNode(this.refs.text));
+    if (!this.state.width) {
+      this.setState({ width });
+    } else if (width !== this.state.width) {
+      this.setState({ width }, this.reset); // trigger this.verifyOverflow
+    }
+  };
+
   verifyOverflow = () => {
     if (this.state.isOverflowing === false && typeof window !== 'undefined') {
```
Comment (FrancescoCioria) [inline src/text-overflow/TextOverflow.js]: `this.state.isOverflowing === false` is the only 100% effective way I found to avoid infinite loops ( #117 )

File: src/text-overflow/TextOverflow.js [hunk 2]
```diff
@@ -54,21 +64,35 @@ export default class TextOverflow extends React.Component {
...
       const text = ReactDOM.findDOMNode(this.refs.text);
       const textWithoutEllipsis = ReactDOM.findDOMNode(this.refs.textWithoutEllipsis);
 
-      if (text && textWithoutEllipsis) {
```
Comment (FrancescoCioria) [inline src/text-overflow/TextOverflow.js]: this `if` shouldn't be necessary anymore ad I'm clearing `this.interval` and `this.timeout` in `componentWillUnmount`

File: src/text-overflow/TextOverflow.js [hunk 3]
```diff
@@ -54,21 +64,35 @@ export default class TextOverflow extends React.Component {
...
 
-        const isOverflowing = (textWidth < textWithoutEllipsisWidth);
-        if (isOverflowing) {
-          this.setState({ isOverflowing: true }, this.logWarnings);
-        } else {
-          this.logWarnings();
-        }
+      const isOverflowing = (textWidth < textWithoutEllipsisWidth);
+      if (isOverflowing) {
+        this.setState({ isOverflowing: true, width: null }, this.logWarnings);
```
Comment (FrancescoCioria) [inline src/text-overflow/TextOverflow.js]: I'm setting `width` to `null` to reset the behavior of `this.verifySize`

File: src/text-overflow/TextOverflow.js [hunk 4]
```diff
@@ -25,12 +25,22 @@ export default class TextOverflow extends React.Component {
...
   constructor(props) {
     super(props);
-    this.state = { isOverflowing: false };
+    this.state = { isOverflowing: false, width: null };
   }
 
-  componentDidMount = () => setTimeout(this.verifyOverflow);
+  componentDidMount() {
+    setTimeout(this.verifyOverflow);
+    this.interval = setInterval(this.verifySize, 100);
```
Comment (FrancescoCioria) [inline src/text-overflow/TextOverflow.js]: `100` looks very arbitrary.... maybe we could increase it?

File: src/text-overflow/TextOverflow.js [hunk 5]
```diff
@@ -25,12 +25,22 @@ export default class TextOverflow extends React.Component {
...
   constructor(props) {
     super(props);
-    this.state = { isOverflowing: false };
+    this.state = { isOverflowing: false, width: null };
   }
 
-  componentDidMount = () => setTimeout(this.verifyOverflow);
+  componentDidMount() {
+    this.timeout = setTimeout(this.verifyOverflow);
+    this.interval = setInterval(this.verifySize, 100);
```
Comment (FrancescoCioria) [inline src/text-overflow/TextOverflow.js]: (maybe make `100` overridable through `props`?)

**Comment by FrancescoCioria** [comment]
@giogonzo tested successfully on LOL (table header resize)
